version: "3.7"

services:
  server:
    image: '${DOCKER_IMAGE_BACKEND-server}:${TAG-latest}'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

volumes:
  app-db-data:
  redis:
